[workspace]
members = ["src/day_1_task_1"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
tracing = { version = "0.1.43" }
tracing-subscriber = { version = "0.3.22" }
