[package]
name = "day2"
edition.workspace = true
version.workspace = true

[[bin]]
name = "day2"
path = "main.rs"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
color-eyre = { workspace = true }
