[package]
name = "day_1_task_1"
edition.workspace = true
version.workspace = true

[[bin]]
name = "day_1_task_1"
path = "main.rs"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
